#!/usr/bin/env bash

export PLUGIN_COMMAND_PREFIX="snapshot"
export PLUGIN_DATA_ROOT="${DOKKU_LIB_ROOT:-/var/lib/dokku}/data/snapshot"

export DOKKU_BIN="${DOKKU_BIN:-/usr/bin/dokku}"
PLUGIN_BASE_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PLUGIN_BASE_PATH
